version: '3.4'

services:
  catalogdb:
    image: postgres 
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog.Api/Dockerfile

volumes:    
  postgres_catalog:

 
